### ISSUE TITLE
OPFS is not available in Safari

### ISSUE THREAD

**Issue by jlia0** [tomayac/sqlite-wasm#17]
Any fixes to run SQLite WASM on Safari?

<img width="1546" alt="image" src="https://github.com/tomayac/sqlite-wasm/assets/24471281/338f709d-a58c-470f-977a-c19ff9dc0c01">

**Comment by sgbeal** [comment]
Nope. This is/was a Safari bug which has reportedly been fixed for the next browser release. There's nothing we can do to make it work until then.

**Comment by chrisamador** [comment]
Hi @sgbeal, for those following this issue, is this Safari bug you are referring to? https://bugs.webkit.org/show_bug.cgi?id=22723. Thanks.

**Comment by sgbeal** [comment]
No, it was a bug in the handling of the storage API from subworkers which caused the storage API to not work there. i don't have the ticket link anywhere convenient - it's buried in the sqlite forum somewhere.

**Comment by steida** [comment]
@sgbeal If I put all queries and mutations into a queue via Web Locks API, am I good? Anyway, thank you for visiting this place. It's really helpful.

**Comment by sgbeal** [comment]
For the new VFS web locks won't help. Because of the shape of the OPFS API, it has to acquire and hold on to exclusive locks for its whole lifetime. It would hypothetically be possible to shut it down and restart it in order to coordinate between two tabs which coordinate via web locks, but that would be slow and i'm not yet certain whether it's practical to implement in the VFS. We have a way to shut it down but the ability to restart it has not yet been developed.

**Comment by steida** [comment]
So it's one tab only. So other tabs would have to use that one tab, and if closed, a random other tab would have to become the main. That should be possible with lazy init. Am I correct?

**Comment by sgbeal** [comment]
It's effectively one tab per instance, but multiple instances can coexist, each with their own private storage space and no shared space. (That allows multiple pages on a site to each use the VFS, they just can't share any data.) Any sort of leader/follower management lies way out of the library's scope, so it's not something i've given any thought to. IIRC, [Roy H.](https://github.com/rhashimoto/wa-sqlite) has experimented with such a configuration with his VFSes.
